/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Employees
         * @description Employees ordered by ID, with local recommendation status; no employee ranking.
         */
        get: operations["list_employees_api_employees_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Import
         * @description Atomically upsert profiles and history; recommendations are immediately available.
         */
        post: operations["post_import_api_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description Aggregate current/next-grade gaps, missing steps and participation without ranking people.
         */
        get: operations["get_summary_api_hr_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Employee */
        get: operations["get_employee_api_employees__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees/{id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recommendations
         * @description Recommend eligible events using explicit scores and validated optional LLM selection.
         */
        get: operations["get_recommendations_api_employees__id__recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Completion
         * @description Apply skill growth atomically; replay the saved response for the same completion key.
         */
        post: operations["post_completion_api_employees__id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityHistory */
        ActivityHistory: {
            /**
             * Synthetic
             * @default false
             */
            synthetic?: boolean;
            /** Employee Id */
            employee_id: string;
            /** Event Id */
            event_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "in_progress" | "dropped" | "no_show" | "declined" | "overdue";
            /** Record Id */
            record_id?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Completion Pct */
            completion_pct?: number | null;
            /** Score */
            score?: number | null;
            /** Feedback Rating */
            feedback_rating?: number | null;
            /** Assigned By */
            assigned_by?: ("self" | "manager" | "hr") | null;
        };
        /** ActivityParticipation */
        ActivityParticipation: {
            /** Event Id */
            event_id: string;
            /** Title */
            title: string | null;
            /**
             * Enrolled
             * @description All participation records, including completed ones
             */
            enrolled: number;
            /** Completed */
            completed: number;
            /** Missed */
            missed: number;
            /** Declined */
            declined: number;
            /** In Progress */
            in_progress: number;
            /** Dropped */
            dropped: number;
            /** Overdue */
            overdue: number;
        };
        /** Audience */
        Audience: {
            /** Roles */
            roles: string[];
            /** Grades */
            grades: ("Junior" | "Middle" | "Senior" | "Lead")[];
        };
        /** CareerGoal */
        CareerGoal: {
            /** Target Role */
            target_role: string;
            /**
             * Target Grade
             * @enum {string}
             */
            target_grade: "Junior" | "Middle" | "Senior" | "Lead";
        };
        /** CompleteRequest */
        CompleteRequest: {
            /** Event Id */
            event_id: string;
            /** Completion Id */
            completion_id: string;
        };
        /** CompletionResponse */
        CompletionResponse: {
            /** Employee Id */
            employee_id: string;
            /** Event Id */
            event_id: string;
            /** Completion Id */
            completion_id: string;
            /**
             * Status
             * @constant
             */
            status: "completed";
            /** Skills Before */
            skills_before: {
                [key: string]: number;
            };
            /** Skills After */
            skills_after: {
                [key: string]: number;
            };
            progress_after: components["schemas"]["GradeProgress"];
        };
        /** EmployeeListItem */
        EmployeeListItem: {
            /**
             * Synthetic
             * @default false
             */
            synthetic?: boolean;
            /** Employee Id */
            employee_id: string;
            /** Role */
            role: string;
            /**
             * Grade
             * @enum {string}
             */
            grade: "Junior" | "Middle" | "Senior" | "Lead";
            /** Tenure Months */
            tenure_months: number;
            /** Skills */
            skills: {
                [key: string]: number;
            };
            /** Full Name */
            full_name?: string | null;
            /** Department */
            department?: string | null;
            /** Manager Id */
            manager_id?: string | null;
            /** Hire Date */
            hire_date?: string | null;
            /** Work Format */
            work_format?: ("office" | "hybrid" | "remote") | null;
            /** Preferred Language */
            preferred_language?: ("kk" | "ru" | "en") | null;
            career_goal?: components["schemas"]["CareerGoal"] | null;
            /** Last Review Date */
            last_review_date?: string | null;
            /**
             * Recommendation Status
             * @enum {string}
             */
            recommendation_status: "ready" | "no_suitable_event" | "requirements_met";
            /** Next Grade */
            next_grade: ("Junior" | "Middle" | "Senior" | "Lead") | null;
        };
        /** EmployeeProfile */
        EmployeeProfile: {
            /**
             * Synthetic
             * @default false
             */
            synthetic?: boolean;
            /** Employee Id */
            employee_id: string;
            /** Role */
            role: string;
            /**
             * Grade
             * @enum {string}
             */
            grade: "Junior" | "Middle" | "Senior" | "Lead";
            /** Tenure Months */
            tenure_months: number;
            /** Skills */
            skills: {
                [key: string]: number;
            };
            /** Full Name */
            full_name?: string | null;
            /** Department */
            department?: string | null;
            /** Manager Id */
            manager_id?: string | null;
            /** Hire Date */
            hire_date?: string | null;
            /** Work Format */
            work_format?: ("office" | "hybrid" | "remote") | null;
            /** Preferred Language */
            preferred_language?: ("kk" | "ru" | "en") | null;
            career_goal?: components["schemas"]["CareerGoal"] | null;
            /** Last Review Date */
            last_review_date?: string | null;
            progress: components["schemas"]["GradeProgress"];
            /** History */
            history: components["schemas"]["ActivityHistory"][];
        };
        /** EmployeeStep */
        EmployeeStep: {
            /** Employee Id */
            employee_id: string;
            /** Full Name */
            full_name: string | null;
            /** Role */
            role: string;
            /**
             * Grade
             * @enum {string}
             */
            grade: "Junior" | "Middle" | "Senior" | "Lead";
            /** Next Grade */
            next_grade: ("Junior" | "Middle" | "Senior" | "Lead") | null;
        };
        /** EmployeesResponse */
        EmployeesResponse: {
            /** Employees */
            employees: components["schemas"]["EmployeeListItem"][];
            /** Total */
            total: number;
        };
        /** EmployeesWithoutStep */
        EmployeesWithoutStep: {
            /** Requirements Met */
            requirements_met: components["schemas"]["EmployeeStep"][];
            /** No Suitable Event */
            no_suitable_event: components["schemas"]["EmployeeStep"][];
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** Event */
        Event: {
            /**
             * Synthetic
             * @default false
             */
            synthetic?: boolean;
            /** Event Id */
            event_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "compliance" | "onboarding" | "course" | "workshop" | "mentoring" | "certification" | "meetup";
            audience: components["schemas"]["Audience"];
            /** Skills */
            skills: components["schemas"]["SkillGain"][];
            /** Title */
            title?: string | null;
            /**
             * Description
             * @default
             */
            description?: string;
            /** Format */
            format?: ("online" | "offline" | "self_paced") | null;
            /** Duration Hours */
            duration_hours?: number | null;
            /**
             * Mandatory
             * @default false
             */
            mandatory?: boolean;
            /** Prerequisites */
            prerequisites?: {
                [key: string]: number;
            };
            /** Upcoming Sessions */
            upcoming_sessions?: string[];
        };
        /** GradeProgress */
        GradeProgress: {
            /**
             * Status
             * @enum {string}
             */
            status: "needs_development" | "requirements_met" | "no_next_grade";
            /** Next Grade */
            next_grade: ("Junior" | "Middle" | "Senior" | "Lead") | null;
            requirements: components["schemas"]["GradeRequirement"] | null;
            /** Gaps */
            gaps: components["schemas"]["SkillGap"][];
            /**
             * Remaining Points
             * @description Sum of skill deficits for the next grade
             */
            remaining_points: number;
        };
        /** GradeRequirement */
        GradeRequirement: {
            /**
             * Synthetic
             * @default false
             */
            synthetic?: boolean;
            /** Role */
            role: string;
            /**
             * Grade
             * @enum {string}
             */
            grade: "Junior" | "Middle" | "Senior" | "Lead";
            /** Required Skills */
            required_skills: {
                [key: string]: number;
            };
            /** Critical Skills */
            critical_skills?: string[];
        };
        /** HRSummaryResponse */
        HRSummaryResponse: {
            /**
             * Status
             * @constant
             */
            status: "ready";
            /** Total Employees */
            total_employees: number;
            /** Total Events */
            total_events: number;
            /** Completed Activities */
            completed_activities: number;
            /** Employees By Grade */
            employees_by_grade: {
                [key: string]: number;
            };
            /** Current Grade Skill Gaps */
            current_grade_skill_gaps: components["schemas"]["SkillDeficiency"][];
            /** Next Grade Skill Gaps */
            next_grade_skill_gaps: components["schemas"]["SkillDeficiency"][];
            employees_without_step: components["schemas"]["EmployeesWithoutStep"];
            /** Participation By Event */
            participation_by_event: components["schemas"]["ActivityParticipation"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportFieldError */
        ImportFieldError: {
            /** Loc */
            loc: (string | number)[];
            /** Msg */
            msg: string;
            /** Type */
            type: string;
        };
        /** ImportResponse */
        ImportResponse: {
            /**
             * Status
             * @constant
             */
            status: "imported";
            /** Employees Received */
            employees_received: number;
            /** History Received */
            history_received: number;
            /** Employees Imported */
            employees_imported: number;
            /** History Imported */
            history_imported: number;
            /** Employees Created */
            employees_created: number;
            /** Employees Updated */
            employees_updated: number;
            /** History Created */
            history_created: number;
            /** History Updated */
            history_updated: number;
        };
        /** ImportValidationResponse */
        ImportValidationResponse: {
            /** Detail */
            detail: components["schemas"]["ImportFieldError"][];
        };
        /** Recommendation */
        Recommendation: {
            event: components["schemas"]["Event"];
            /** Score */
            score: number;
            /** Reasons */
            reasons: string[];
            factors: components["schemas"]["RecommendationFactors"];
            /** Explanation */
            explanation: string;
        };
        /** RecommendationFactors */
        RecommendationFactors: {
            /**
             * Employee Grade
             * @enum {string}
             */
            employee_grade: "Junior" | "Middle" | "Senior" | "Lead";
            /**
             * Target Grade
             * @enum {string}
             */
            target_grade: "Junior" | "Middle" | "Senior" | "Lead";
            /** Audience Grade Count */
            audience_grade_count: number;
            /** Skill Impacts */
            skill_impacts: components["schemas"]["SkillImpact"][];
            /** Total Deficit */
            total_deficit: number;
            /** Covered Deficit */
            covered_deficit: number;
            /** Weighted Total Deficit */
            weighted_total_deficit: number;
            /** Weighted Covered Deficit */
            weighted_covered_deficit: number;
            /** Similar Event Ids */
            similar_event_ids: string[];
            /** No Show Count */
            no_show_count: number;
            /** Declined Count */
            declined_count: number;
            /** Deficit Score */
            deficit_score: number;
            /** Importance Score */
            importance_score: number;
            /** Grade Score */
            grade_score: number;
            /** History Penalty */
            history_penalty: number;
            weights: components["schemas"]["ScoringWeights"];
        };
        /** RecommendationsResponse */
        RecommendationsResponse: {
            /** Employee Id */
            employee_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "no_suitable_event" | "requirements_met";
            /**
             * Source
             * @enum {string}
             */
            source: "fallback" | "llm";
            /** Next Grade */
            next_grade: ("Junior" | "Middle" | "Senior" | "Lead") | null;
            /** Recommendations */
            recommendations: components["schemas"]["Recommendation"][];
            /** Gaps */
            gaps: components["schemas"]["SkillGap"][];
        };
        /** ScoringWeights */
        ScoringWeights: {
            /**
             * Deficit
             * @default 100
             */
            deficit?: number;
            /**
             * Importance
             * @default 30
             */
            importance?: number;
            /**
             * Grade
             * @default 5
             */
            grade?: number;
            /**
             * No Show
             * @default 10
             */
            no_show?: number;
            /**
             * Declined
             * @default 15
             */
            declined?: number;
            /**
             * History Penalty Cap
             * @default 30
             */
            history_penalty_cap?: number;
        };
        /** SkillDeficiency */
        SkillDeficiency: {
            /** Skill Id */
            skill_id: string;
            /** Name */
            name: string;
            /** Employees Affected */
            employees_affected: number;
            /** Employees Assessed */
            employees_assessed: number;
            /** Total Deficit */
            total_deficit: number;
        };
        /** SkillGain */
        SkillGain: {
            /** Skill Id */
            skill_id: string;
            /** Gain */
            gain: number;
            /** Max Level */
            max_level: number;
        };
        /** SkillGap */
        SkillGap: {
            /** Skill Id */
            skill_id: string;
            /** Current Level */
            current_level: number;
            /** Required Level */
            required_level: number;
            /** Deficit */
            deficit: number;
        };
        /** SkillImpact */
        SkillImpact: {
            /** Skill Id */
            skill_id: string;
            /** Current Level */
            current_level: number;
            /** Required Level */
            required_level: number;
            /** Deficit */
            deficit: number;
            /** Gain */
            gain: number;
            /** Max Level */
            max_level: number;
            /** Level After */
            level_after: number;
            /** Effective Gain */
            effective_gain: number;
            /** Covered Deficit */
            covered_deficit: number;
            /** Critical */
            critical: boolean;
            /** Importance */
            importance: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_employees_api_employees_get: {
        parameters: {
            query?: never;
            header?: {
                "x-role"?: ("employee" | "hr") | null;
                "x-employee-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeesResponse"];
                };
            };
            /** @description Missing identity headers */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Employee or event not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_import_api_import_post: {
        parameters: {
            query?: never;
            header?: {
                "x-role"?: ("employee" | "hr") | null;
                "x-employee-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** DatasetMeta */
                    meta?: {
                        /**
                         * Dataset
                         * @default Career Quest
                         */
                        dataset?: string;
                        /**
                         * Version
                         * @default 1.0
                         */
                        version?: string;
                        /** As Of Date */
                        as_of_date?: string | null;
                        /**
                         * Synthetic
                         * @default false
                         */
                        synthetic?: boolean;
                    };
                    /** Employees */
                    employees: {
                        /**
                         * Synthetic
                         * @default false
                         */
                        synthetic?: boolean;
                        /** Employee Id */
                        employee_id: string;
                        /** Role */
                        role: string;
                        /**
                         * Grade
                         * @enum {string}
                         */
                        grade: "Junior" | "Middle" | "Senior" | "Lead";
                        /** Tenure Months */
                        tenure_months: number;
                        /** Skills */
                        skills: {
                            [key: string]: number;
                        };
                        /** Full Name */
                        full_name?: string | null;
                        /** Department */
                        department?: string | null;
                        /** Manager Id */
                        manager_id?: string | null;
                        /** Hire Date */
                        hire_date?: string | null;
                        /** Work Format */
                        work_format?: ("office" | "hybrid" | "remote") | null;
                        /** Preferred Language */
                        preferred_language?: ("kk" | "ru" | "en") | null;
                        career_goal?: {
                            /** Target Role */
                            target_role: string;
                            /**
                             * Target Grade
                             * @enum {string}
                             */
                            target_grade: "Junior" | "Middle" | "Senior" | "Lead";
                        } | null;
                        /** Last Review Date */
                        last_review_date?: string | null;
                    }[];
                    /** History */
                    history: {
                        /**
                         * Synthetic
                         * @default false
                         */
                        synthetic?: boolean;
                        /** Employee Id */
                        employee_id: string;
                        /** Event Id */
                        event_id: string;
                        /**
                         * Date
                         * Format: date
                         */
                        date: string;
                        /**
                         * Status
                         * @enum {string}
                         */
                        status: "completed" | "in_progress" | "dropped" | "no_show" | "declined" | "overdue";
                        /** Record Id */
                        record_id?: string | null;
                        /** Due Date */
                        due_date?: string | null;
                        /** Completion Pct */
                        completion_pct?: number | null;
                        /** Score */
                        score?: number | null;
                        /** Feedback Rating */
                        feedback_rating?: number | null;
                        /** Assigned By */
                        assigned_by?: ("self" | "manager" | "hr") | null;
                    }[];
                };
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description employees.json: dataset envelope or Employee array
                     */
                    employees_file: string;
                    /**
                     * Format: binary
                     * @description activity_history.csv or JSON history envelope/array
                     */
                    history_file: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            /** @description Missing identity headers */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Employee or event not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Uploaded file exceeds 10 MiB */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported content type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Field validation or reference errors */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportValidationResponse"];
                };
            };
        };
    };
    get_summary_api_hr_summary_get: {
        parameters: {
            query?: never;
            header?: {
                "x-role"?: ("employee" | "hr") | null;
                "x-employee-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HRSummaryResponse"];
                };
            };
            /** @description Missing identity headers */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Employee or event not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_employee_api_employees__id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-role"?: ("employee" | "hr") | null;
                "x-employee-id"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeProfile"];
                };
            };
            /** @description Missing identity headers */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Employee or event not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommendations_api_employees__id__recommendations_get: {
        parameters: {
            query?: never;
            header?: {
                "x-role"?: ("employee" | "hr") | null;
                "x-employee-id"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationsResponse"];
                };
            };
            /** @description Missing identity headers */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Employee or event not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_completion_api_employees__id__complete_post: {
        parameters: {
            query?: never;
            header?: {
                "x-role"?: ("employee" | "hr") | null;
                "x-employee-id"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionResponse"];
                };
            };
            /** @description Event audience does not match employee */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing identity headers */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Employee or event not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Stored completion has no replay response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
